HTML_Python/LITReview/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
import authentication.views
import blog.views
import connected.views

urlpatterns = [
    path("admin/", admin.site.urls),
    # URL d'authentification
    path("", authentication.views.login_page, name='login'),
    path("logout/", authentication.views.logout_page, name="logout"),
    # URL de connexion
    path("home/", connected.views.home, name="home"),
    # URL d'inscription
    path("inscription/", authentication.views.inscription_page, name="inscription"),
    # URL page personnel
    path("home/page_personnel/", connected.views.page_personnel, name="page_personnel"),
    # URL création de ticket et critique
    path("blog/creation_ticket/", blog.views.creation_ticket, name="creation_ticket"),
    path("blog/creation_critique_vide/", blog.views.creation_critique_vide, name="creation_critique_vide"),
    path("blog/creation_critique_liee/<int:ticket_id>/", blog.views.creation_critique_liee, name="creation_critique_liee"),
    # URL affichage des tickets
    path("blog/affichage_des_tickets/", blog.views.affichage_des_tickets, name="affichage_des_tickets"),
    path("blog/affichage_dun_ticket/<int:ticket_id>/", blog.views.affichage_dun_ticket, name="affichage_dun_ticket"),
    # URL modification des tickets/critiques
    path("blog/modification_critique/<int:critique_id>/", blog.views.modification_critique, name="modification_critique"),
    path("blog/modification_ticket/<int:ticket_id>/", blog.views.modification_ticket, name="modification_ticket"),
    # URL suppression des tickets/critiques
    path("blog/suppression_critique/<int:critique_id>/", blog.views.suppression_critique, name="suppression_critique"),
    path("blog/suppression_ticket/<int:ticket_id>/", blog.views.suppression_ticket, name="suppression_ticket"),
    # URL gestion des utilisateurs
    path("connected/gestion_utilisateur/", connected.views.gestion_utilisateur, name="gestion_utilisateur"),
    # URL abonnement utilisateur
    path("connected/abonnement_utilisateur/", connected.views.abonnement_utilisateur, name="abonnement_utilisateur"),
    path("connected/follow_user/", connected.views.follow_user, name="follow_user")
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HTML_Python/authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group


class User(AbstractUser):
    # Deux profils possible "Utilisateur" ou "Administrateur"
    UTILISATEUR = "UTILISATEUR"
    ADMINISTRATEUR = "ADMINISTRATEUR"

    ROLE_CHOICES = (
        {UTILISATEUR, "Utilisateur"},
        {ADMINISTRATEUR, "Administrateur"}
    )

    nombre_ticket = models.fields.IntegerField(default=0,
                                               verbose_name="Nombre de ticket")
    nombre_critique = models.fields.IntegerField(default=0,
                                                 verbose_name="Nombre de critique")
    role = models.CharField(max_length=30,
                            choices=ROLE_CHOICES,
                            default="Utilisateur")
    abonnement = models.ManyToManyField('self',
                                        symmetrical=False,
                                        blank=True,
                                        related_name="followed_by")
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.role == "Utilisateur":
            group = Group.objects.get(name='Utilisateur')
            group.user_set.add(self)
        elif self.role == "Administrateur":
            group = Group.objects.get(name='Administrateur')
            group.user_set.add(self)

HTML_Python/connected/models.py
# from django.db import models

# Create your models here.

HTML_Python/connected/forms.py
from django import forms
# Récupération du modèle prédéfini UserCreationForm
from authentication.models import User


class ModificationUtilisateur(forms.ModelForm):
    edit_user = forms.BooleanField(widget=forms.HiddenInput,
                                   initial=True)

    class Meta:
        # Import du modèle User
        model = User
        fields = ["role"]

HTML_Python/connected/views.py
from django.shortcuts import render, redirect
# from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.decorators import login_required
from authentication.models import User
from . import forms
from blog.models import Ticket, Critique
from itertools import chain
from operator import attrgetter


@login_required
def page_personnel(request):
    tickets = Ticket.objects.all()
    critiques = Critique.objects.all()
    mes_tickets = []
    mes_critiques = []
    for ticket in tickets:
        if ticket.auteur == request.user:
            mes_tickets.append(ticket)

    for critique in critiques:
        if critique.auteur == request.user:
            mes_critiques.append(critique)

    return render(request,
                  "connected/page_personnel.html",
                  context={"tickets": mes_tickets,
                           "critiques": mes_critiques})


@login_required
# @permission_required ("gestion_utilisateur", raise_exception=True)
def gestion_utilisateur(request):
    utilisateurs = User.objects.all()
    utilisateur = User(request)
    form_utilisateur = forms.ModificationUtilisateur()
    if request.method == "POST":
        # Récupére la liste des roles de la méthode POST
        liste_role = request.POST.getlist('role')
        rang = 0
        if request.user.role == "Administrateur":
            for utilisateur in utilisateurs:
                # Ne modifie que les autres utilisateurs
                if utilisateur != request.user:
                    # Affecte les roles suivant la liste des utilisateurs
                    utilisateur.role = liste_role[rang]
                    utilisateur.save()
                    rang += 1
        else:
            return redirect("home")

    return render(request,
                  "connected/gestion_utilisateur.html",
                  context={"utilisateurs": utilisateurs,
                           "form_utilisateur": form_utilisateur})


@login_required
def home(request):
    # Tri des tickets et critiques par ordre décroissant de création
    # Donc du plus rescent ou plus ancien
    # N'affiche que les 5 premieres réponses
    # tickets = Ticket.objects.all().order_by("-date_creation")[:5]
    tickets = Ticket.objects.all()
    critiques = Critique.objects.all()
    abonnements = request.user.abonnement.all()
    # Regroupe les tickets et les critiques dans la meme liste
    # et les tris par date de création
    flux_global = []
    flux_global = sorted(chain(tickets, critiques),
                         key=attrgetter('date_creation'),
                         reverse=True)
    return render(request,
                  "connected/home.html",
                  context={"flux_global":flux_global,
                           "abonnements": abonnements})


@login_required
def abonnement_utilisateur(request):
    utilisateurs = User.objects.all()
    abonnements = request.user.abonnement.all()
    # Regarde si c'est une méthode POST
    if request.method == "POST":
        # si le bouton est "suivre" on rajoute à la base de donnée
        if request.POST.get("suivre"):
            request.user.abonnement.add(request.POST.get("suivre"))
        # Si le bouton est "ne plus suivre" on enleve de la base de donnée
        elif request.POST.get("ne_plus_suivre"):
            request.user.abonnement.remove(request.POST.get("ne_plus_suivre"))
    return render(request,
                  "connected/abonnement_utilisateur.html",
                  context={"utilisateurs": utilisateurs,
                           "abonnements": abonnements})


def follow_user(request):
    follow_user = User.objects.get(pk=request.user.id)

    if request.method == "POST":
        current_user_profile = request.user
        action = request.POST['follow']
        if action == "unfollow":
            current_user_profile.follows.remove(follow_user)
        elif action == "follow":
            current_user_profile.follows.add(follow_user)

    return render(request,
                  'connected/newuser_detail.html',
                  {"follow_user": follow_user})

HTML_Python/connected/templates/connected/abonnement_utilisateur.html
{% extends 'base_connecte.html' %}

{% block en-tete %}
    Mes abonnements
{% endblock en-tete %}

{% block content %}
    <h2>Suivre des utilisateurs</h2>
        <form method="post" enctype="multipart/form-data" class="tableau">
            <table>
                <tr>
                    <th>Utilisateur</th>
                    <th>Nombre de ticket</th>
                    <th>Nombre de critique</th>
                    <th>Abonnement</th>
                </tr>
            
                {% for utilisateur in utilisateurs %}
                    {% if utilisateur != request.user %}
                        <tr>
                            <td>{{utilisateur.username}}</td>
                            <td>{{utilisateur.nombre_ticket}}</td>
                            <td>{{utilisateur.nombre_critique}}</td>
                            <td>{% if utilisateur in abonnements%}
                                <button type="submit" name="ne_plus_suivre" value={{utilisateur.id}}>
                                    Ne plus suivre
                                </button>
                            {% else %}
                                <button type="submit" name="suivre" value={{utilisateur.id}}>
                                    Suivre
                                </button>
                            {% endif %}</td>
                        </tr>
                    {% endif %}    
                {% endfor %}
            </table>
            {% csrf_token %}
    </form>
{% endblock content %}

HTML_Python/connected/templates/connected/gestion_utilisateur.html
{% extends 'base_connecte.html' %}

{% block en-tete %}
    Gestion des utilisateurs
{% endblock en-tete %}

{% block content %}
    <p>Ici la gestion des utilisateurs</p>
    <form method="post" enctype="multipart/form-data" class="tableau">
        <table>
            <tr>
                <th>Utilisateur</th>
                <th>Nombre de ticket</th>
                <th>Nombre de critique</th>
                <th>Profil</th>
            </tr>
            {%for utilisateur in utilisateurs%}
                <tr>
                    <td>{{utilisateur.username}}</td>
                    <td>{{utilisateur.nombre_ticket}}</td>
                    <td>{{utilisateur.nombre_critique}}</td>
                    <!--Empeche l'utilisateur connecté de modifier son profil-->
                    {%if request.user == utilisateur %}
                        <td>{{utilisateur.role}}</td>
                    {% else %}
                        <td>
                            <select name="role" id="id_role">
                                {% if utilisateur.role == "Utilisateur" %}
                                    <option value="Utilisateur" selected>Utilisateur</option>
                                    <option value="Administrateur">Administrateur</option>
                                {% else %}
                                    <option value="Utilisateur" >Utilisateur</option>
                                    <option value="Administrateur" selected>Administrateur</option>
                                {% endif %}
                            </select>
                        </td>
                    {% endif %}
                    <td>{{utilisateur.role}}</td>
                </tr>
            {% endfor %}
        </table>
        {% csrf_token %}
        <button type="submit">Valider les changements</button>
    </form>
{% endblock content %}

HTML_Python/connected/templates/connected/home.html
{% extends 'base_connecte.html' %}

{% block en-tete %}
    Bienvenue {{ request.user }}
{% endblock en-tete %}

{% block content %}
    <h2>Voici les dernières nouveautés</h2>
    <!-- Affiche la liste des tickets -->
    {% for article in flux_global %}
        {% if article.titre_ticket %}
            <table class="tableau_accueil tableau_ticket">
                <tr>
                    {% if request.user != article.auteur%}
                        <th colspan="4">Ticket posté le {{article.date_creation}} par {{article.auteur}}</th>
                    {% else %}
                        <th colspan="4">Ticket que vous avez posté le {{article.date_creation}}</th>
                    {% endif %}                    
                </tr>
                <tr>
                    {% if request.user != article.auteur%}
                        {% if article.auteur in abonnements%}
                            <td class="follower" rowspan="4">
                                Ceci <br>
                                a été posté <br>
                                par un <br>
                                utilisateur<br>
                                que vous suivez
                            </td>
                        {% endif %}
                    {% endif %}
                    <td class="titre">Titre</td>
                    <td rowspan="4">
                        <img src="{{ article.illustration.url }}"
                        alt="Image du ticket : {{article.titre_ticket}}"
                        title ="{{article.titre_ticket}}">
                    </td>
                    <td rowspan="4"> <a href="{% url 'affichage_dun_ticket' article.id %}">Aperçu</td>
                </tr>
                <tr>
                    <td>{{article.titre_ticket}}</td>
                </tr>
                <tr>
                    <td class="titre">Description</td>
                </tr>
                <tr>
                    <td>{{article.description}}</td>
                </tr>
            </table>

        {% elif article.titre_critique %}
            <table class="tableau_accueil tableau_critique">
                <tr>
                    {% if request.user != article.auteur%}
                        <th colspan="4">Critique postée le {{article.date_creation}} par {{article.auteur}}<br>
                                        En réponse au ticket : {{article.ticket}}</th>
                    {% else %}
                        <th colspan="4">Critique que vous avez posté le {{article.date_creation}}<br>
                                        En réponse au ticket : {{article.ticket}}</th>
                    {% endif %}                    
                </tr>
                <tr>
                    {% if request.user != article.auteur%}
                        {% if article.auteur in abonnements%}
                            <td class="follower" rowspan="4">
                                Ceci <br>
                                a été posté <br>
                                par un <br>
                                utilisateur<br>
                                que vous suivez
                            </td>
                        {% endif %}
                    {% endif %}
                    <th class="titre">Note</th>
                    <th class="titre">Titre</th>
                    <td rowspan="4"> <a href="{% url 'affichage_dun_ticket' article.ticket.id %}">Aperçu</td>
                </tr>
                <tr>
                    <td>{{article.note}}</td>
                    <td>{{article.titre_critique}}</td>
                </tr>
                <tr>
                    <td colspan="2" class="titre">Commentaire</td>
                </tr>
                <tr>
                    <td colspan="2">{{article.commentaire}}</td>
                </tr>
            </table>
        
        {% endif %}
    {% endfor %}
{% endblock content %}

HTML_Python/connected/templates/connected/page_personnel.html
{% extends 'base_connecte.html' %}

{% block en-tete %}
    Mon profil
{% endblock en-tete %}

{% block content %}
<table class="tableau">
    <caption> Mes Informations </caption>
    <tr>
        <td>Mon nom</td>
        <td>{{request.user}}</td>
    </tr>
    <tr>
        <td>Mon e-mail</td>
        {% if request.user.email == "" %}
            <td>Aucun email de renseigné</td>
        {% else %}
            <td>{{request.user.email}}</td>
        {% endif %}
    </tr>
    <tr>
        <td>Mon nombre de critique</td>
        <td>{{request.user.nombre_critique}}</td>
    </tr>
    <tr>
        <td>Mon nombre de ticket</td>
        <td>{{request.user.nombre_ticket}}</td>
    </tr>
    <tr>
        <td>Mon inscription</td>
        <td>{{request.user.date_joined}}</td>
    </tr>
    <tr>
        <td>Ma derniere connexion</td>
        <td>{{request.user.last_login}}</td>
    </tr>
    <tr>
        <td>Mon role</td>
        <td>{{request.user.role}}</td>
    </tr>
</table>

<table class="tableau">
        <caption>Mes Tickets</caption>
        <tr>
            <th>Titre du ticket</th>
            <th>Nombre de critique</th>
            <th>Lien</th>
        </tr>
        {%for ticket in tickets %}
            <tr>
                <td>{{ticket.titre_ticket}}</td>
                <td>{{ticket.nombre_critique}}</td>
                <td> <a href="{% url 'affichage_dun_ticket' ticket.id %}">Aperçu</td>
            </tr>
        {% endfor %}
</table>

<table class="tableau">
    <caption>Mes Critiques</caption>
    <tr>
        <th>Titre de la critique</th>
        <th>Nom du ticket</th>
        <th>Lien</th>
    </tr>
    {%for critique in critiques %}
        <tr>
            <td>{{critique.titre_critique}}</td>
            <td>{{critique.ticket.titre_ticket}}</td>
            <td> <a href="{% url 'affichage_dun_ticket' critique.ticket.id %}">Aperçu</td>
        </tr>
    {% endfor %}
</table>
{% endblock content %}